/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressRouteImport } from './routes/press'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ResourcesCategoryRouteImport } from './routes/resources.$category'
import { Route as LocationsCityRouteImport } from './routes/locations.$city'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthorsSlugRouteImport } from './routes/authors.$slug'
import { Route as ResourcesCategorySlugRouteImport } from './routes/resources.$category.$slug'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToolsRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ResourcesCategoryRoute = ResourcesCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ResourcesRoute,
} as any)
const LocationsCityRoute = LocationsCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => LocationsRoute,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IndustriesRoute,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CareersRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthorsSlugRoute = AuthorsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthorsRoute,
} as any)
const ResourcesCategorySlugRoute = ResourcesCategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesCategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/locations': typeof LocationsRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/authors/$slug': typeof AuthorsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/locations/$city': typeof LocationsCityRoute
  '/resources/$category': typeof ResourcesCategoryRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/resources/$category/$slug': typeof ResourcesCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/locations': typeof LocationsRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/authors/$slug': typeof AuthorsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/locations/$city': typeof LocationsCityRoute
  '/resources/$category': typeof ResourcesCategoryRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/resources/$category/$slug': typeof ResourcesCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/locations': typeof LocationsRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/authors/$slug': typeof AuthorsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/locations/$city': typeof LocationsCityRoute
  '/resources/$category': typeof ResourcesCategoryRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/resources/$category/$slug': typeof ResourcesCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/authors'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/industries'
    | '/locations'
    | '/portfolio'
    | '/press'
    | '/privacy'
    | '/resources'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/authors/$slug'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/locations/$city'
    | '/resources/$category'
    | '/services/$slug'
    | '/tools/$slug'
    | '/resources/$category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/authors'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/industries'
    | '/locations'
    | '/portfolio'
    | '/press'
    | '/privacy'
    | '/resources'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/authors/$slug'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/locations/$city'
    | '/resources/$category'
    | '/services/$slug'
    | '/tools/$slug'
    | '/resources/$category/$slug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/authors'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/industries'
    | '/locations'
    | '/portfolio'
    | '/press'
    | '/privacy'
    | '/resources'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/authors/$slug'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/locations/$city'
    | '/resources/$category'
    | '/services/$slug'
    | '/tools/$slug'
    | '/resources/$category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AuthorsRoute: typeof AuthorsRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRouteWithChildren
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  LocationsRoute: typeof LocationsRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/resources/$category': {
      id: '/resources/$category'
      path: '/$category'
      fullPath: '/resources/$category'
      preLoaderRoute: typeof ResourcesCategoryRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/locations/$city': {
      id: '/locations/$city'
      path: '/$city'
      fullPath: '/locations/$city'
      preLoaderRoute: typeof LocationsCityRouteImport
      parentRoute: typeof LocationsRoute
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof CareersRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/authors/$slug': {
      id: '/authors/$slug'
      path: '/$slug'
      fullPath: '/authors/$slug'
      preLoaderRoute: typeof AuthorsSlugRouteImport
      parentRoute: typeof AuthorsRoute
    }
    '/resources/$category/$slug': {
      id: '/resources/$category/$slug'
      path: '/$slug'
      fullPath: '/resources/$category/$slug'
      preLoaderRoute: typeof ResourcesCategorySlugRouteImport
      parentRoute: typeof ResourcesCategoryRoute
    }
  }
}

interface AuthorsRouteChildren {
  AuthorsSlugRoute: typeof AuthorsSlugRoute
}

const AuthorsRouteChildren: AuthorsRouteChildren = {
  AuthorsSlugRoute: AuthorsSlugRoute,
}

const AuthorsRouteWithChildren =
  AuthorsRoute._addFileChildren(AuthorsRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CareersRouteChildren {
  CareersSlugRoute: typeof CareersSlugRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersSlugRoute: CareersSlugRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

interface IndustriesRouteChildren {
  IndustriesSlugRoute: typeof IndustriesSlugRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesSlugRoute: IndustriesSlugRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface LocationsRouteChildren {
  LocationsCityRoute: typeof LocationsCityRoute
}

const LocationsRouteChildren: LocationsRouteChildren = {
  LocationsCityRoute: LocationsCityRoute,
}

const LocationsRouteWithChildren = LocationsRoute._addFileChildren(
  LocationsRouteChildren,
)

interface ResourcesCategoryRouteChildren {
  ResourcesCategorySlugRoute: typeof ResourcesCategorySlugRoute
}

const ResourcesCategoryRouteChildren: ResourcesCategoryRouteChildren = {
  ResourcesCategorySlugRoute: ResourcesCategorySlugRoute,
}

const ResourcesCategoryRouteWithChildren =
  ResourcesCategoryRoute._addFileChildren(ResourcesCategoryRouteChildren)

interface ResourcesRouteChildren {
  ResourcesCategoryRoute: typeof ResourcesCategoryRouteWithChildren
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesCategoryRoute: ResourcesCategoryRouteWithChildren,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface ToolsRouteChildren {
  ToolsSlugRoute: typeof ToolsSlugRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsSlugRoute: ToolsSlugRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AuthorsRoute: AuthorsRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRouteWithChildren,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  LocationsRoute: LocationsRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
